force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To Do</label>
    <nameField>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Action 1</fullName>
            </value>
            <value>
                <fullName>Action 2</fullName>
            </value>
            <value>
                <fullName>Action 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>To Do&apos;s</relationshipLabel>
    <relationshipName>To_Do_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoListControllerTest.cls
@isTest private class ToDoListControllerTest {
    
    @isTest static void testGetToDoList() {
        
        Account acct = new Account(Name = 'TEST ACCT');
        insert acct;
        
        Contact con = new Contact(AccountId = acct.Id, FirstName = 'TEST', LastName='CONTACT');
        insert con;
        
        List<To_Do__c> tdList = new List<To_Do__c>();
        for(Integer i = 0; i < 200; i++) {
            tdList.add(
                new To_Do__c(Name = 'TEST' + i, Contact__c = con.Id, Actions__c = 'Action 1;', Status__c = 'To Do')
            );
        }
        insert tdList;
        
        Test.startTest();
        
        List<To_Do__c> result = ToDoListController.getToDoList(UserInfo.getUserId());
        
        Test.stopTest();
        
        System.assertEquals(200, result.size(), 'ERROR: Unexpected number of To Do records returned.');   
    }
}