force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <label>To Do</label>
    <nameField>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Action 1</fullName>
            </value>
            <value>
                <fullName>Action 2</fullName>
            </value>
            <value>
                <fullName>Action 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>To Do&apos;s</relationshipLabel>
    <relationshipName>To_Do_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoListController.cls
public with sharing class ToDoListController {
    
    @AuraEnabled(cacheable=true)
    public static List<To_Do__c> getToDoList(Id userId){
        return [SELECT Id, Name, Contact__c, Contact__r.Name, Actions__c, Status__c, CreatedDate, CreatedById 
                FROM To_Do__c  WHERE CreatedById =: userId
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC 
                LIMIT 1000];          
    }
}